server:
  port: 8089
spring:
  redis:
    host: 192.168.9.128
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Provide
    registry: zookeeper://192.168.9.128:2181                 #注册中心配置，用于配置连接注册中心相关信息。
    consumer:
      check: false
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
